name: Auto release snapshot

on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - 'dev-*'
  workflow_dispatch:
jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.0
        with:
          # The Java version to make available on the path. Takes a whole or semver Java version, or 1.x syntax (e.g. 1.8 => Java 8.x). Early access versions can be specified in the form of e.g. 14-ea, 14.0.0-ea, or 14.0.0-ea.28
          java-version: 11.0.3

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Build project
        run: |
          ./gradlew clean jar
          sh brew/package.sh
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ steps.extract_branch.outputs.branch }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
        with:
          tag_name: ${{ env.BRANCH_NAME }}-${{ env.GITHUB_RUN_NUMBER }}
          release_name: Release ${{ env.BRANCH_NAME }}-${{ env.GITHUB_RUN_NUMBER }}
          draft: false
          prerelease: true
      - name: Upload Release Asset
        run: |
          set -x
          assets="-a ./build/__restcli__/brew_restcli.zip -a ./build/__restcli__/restcli.zip -a ./build/__restcli__/checksums.txt"
          tag_name="${{ env.BRANCH_NAME }}-${{ env.GITHUB_RUN_NUMBER }}"
          hub release create "${assets}" -m "$tag_name" "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
